### ISSUE TITLE
Additional information links for forum, quiz, & assignment do not work as expected

### ISSUE THREAD

**Issue by timbahula-horizon** [gjbarnard/moodle-format_topcoll#113]
The current links from the additional mod information for forums, quizzes, & assignments do not work as expected in Moodle 3.9. (It appears that this is also true for 3.11.)

For forums, the current link is: `/mod/forum/view.php?action=grading&id=293666&tsort=timesubmitted&filter=require_grading`

The current link is meaningless since forum grading URLS work differently than assignment grading URLs. Unfortunately, forum grading does not appear to have a direct URL. This link would be adequate: `/mod/forum/view.php?id=293666`

For quizzes, the current link is: `/mod/quiz/view.php?action=grading&id=293658&tsort=timesubmitted&filter=require_grading`

This too is meaningless since quiz grading URLS work differently than assignment grading URLs. This link would be suitable for getting to all of the quiz attempts: `/mod/quiz/report.php?id=293658&mode=overview`

Alternatively, this link could be used to get to the interface for questions requiring manual grading: `/mod/quiz/report.php?id=293658&mode=grading`

For assignments, the current link is: `/mod/assign/view.php?action=grading&id=293659&tsort=timesubmitted&filter=require_grading`

This one is closest to working. However, the `filter=require_grading` filter does not work. Changing the filter via the GUI does not result in a URL change. Perhaps the filter cannot be passed by a URL parameter. Further, the `tsort=timesubmitted` filter requires an additional parameter to work properly. Adding `tdir=3` (as in `tsort=timesubmitted&tdir=3`) seems to work as expected. Putting that together: `/mod/assign/view.php?action=grading&id=296385&tsort=timesubmitted&tdir=3`

**Comment by gjb2048** [comment]
Notes:

When 'ungraded' -> 'quiz' from 'overview' to 'grading' 'mode', 'assign' from 'grading' to 'grader' 'action'.

Quiz to change to 'report.php'.

Forum to change to pure view as 'Grading' a JS thing outside of URL control.

**Comment by gjb2048** [comment]
@timbahula-horizon I can replicate all three scenarios.  Technically, this is a bug as the links are not what they should be for the given modules.

**Comment by ghost** [comment]
Hi @gjb2048 , just noticed that this is still an issue in Release 401.0.2, version 2022112601 on Moodle 4.1 (Build: 20221128). Would be great to see it fixed.

While looking at this issue again, I also noticed that the link for additional info on a Choice activity is meaningless too. /mod/choice/view.php?action=grading&id=271150&tsort=timesubmitted&filter=require_grading

I didn't think that deserves a separate issue.

**Comment by gjb2048** [comment]
Note: course_section_cm_get_meta() in format_topcoll\output\courseformat\content\cm needs improving.

@timbahula-horizon A lot on a the moment.  Will get back to this at some point.

**Comment by gjb2048** [comment]
Assign 'timesubmitted', 'tsort' and 'tdir' cannot be found in M4.1 code.

**Comment by ghost** [comment]
Thanks for the update, @gjb2048 , and for your work on this issue. We're not in a hurry.

**Comment by gjb2048** [comment]
Backported to M4.1 version, closing.

**Comment by ghost** [comment]
Thanks, @gjb2048 . Looking forward to getting the new version installed.
