### ISSUE TITLE
Clicking a section takes you to a neighbouring section in some circumstances

### ISSUE THREAD

**Issue by cameron1729** [gjbarnard/moodle-format_topcoll#134]
**Describe the bug**
Clicking a section takes you to a neighbouring section in some circumstances

**To Reproduce**
On Moodle 4.1:
1. Create a course with the Collapsed Columns format and the following settings:
    *  Number of sections : 38
    * Elements: No additions
    *  Column orientation: Horizontal
2. press the "Save and display" button
3. Click on "Section 2" in the left-hand drawer

**Expected behaviour**
"Section 2" is at the top of the page and highlighted in the left hand navigation drawer.

**Actual behaviour**
"Section 1" is at the top of the page and "Section 1" is highlighted in the left hand navigation drawer. Similar behaviour can be observed by clicking "Section 3" and "Section 4" etc.

**Versions (please complete the following information):**
 - Moodle: 4.1.4 (Build: 20230612)
 - Format: MOODLE_401 (commit f89d8d98)
 - Browser and version: Firefox 113.0

**Comment by gjb2048** [comment]
```
/*
ul.ctopics :target::before {
    height: auto;
    margin-top: 0;
    pointer-events: none;
    width: 0;
}
*/
/* Half the navbar height */
ul.ctopics :target {
  scroll-margin-top: 30px;
}
```
