### ISSUE TITLE
Orphaned Section still appear in Index Drawer

### ISSUE THREAD

**Issue by philipblake** [gjbarnard/moodle-format_topcoll#146]
When a section is "orphaned", by reducing the number of sections available to less than the number that have content in on the course page, the orphaned section title still appears in the Index Drawer.

- Create a course with 3 sections.
- Add content to each.
- All 3 sections appear in index drawer.
- Reduce number of sections to 2.
- All 3 sections still appear in index drawer.

![image](https://github.com/gjbarnard/moodle-format_topcoll/assets/11939446/457a4922-ccfe-4091-85b1-7d2236c44b15)

If content is in a later section (e.g. section 20) with no activities in the intervening sections, then all sections are still displayed in the index drawer.

- Create a course with 20 sections.
- Add content to sections 1, 2 and 20.
- All sections appear in index drawer
- Reduced number of sections to 2
- All sections still appear in index drawer

![image](https://github.com/gjbarnard/moodle-format_topcoll/assets/11939446/114594ca-66e6-4be3-8f9e-cbac8e79b272)

Ideally, orphaned sections would not appear in the Index Drawer in non-editing mode.

**Versions you are currently using (please complete the following information):**
 - Moodle: [4.1.8]
 - Format: [401.1.1]
 - Browser and version [Windows 10, Chrome Version 121.0.6167.140 (Official Build) (64-bit)]

** Funding **
Funding available.

**Comment by gjb2048** [comment]
Dear @philipblake,

Appears to be a bug.  Will work on a fix, initially in M4.3.

G
